# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: run
    silent: true
  build:
    cmds:
      - go build -o out/raytracer src/main.go
    sources:
      - src/**/*.go
    generates:
      - out/raytracer
    silent: true
  run:
    deps: [build]
    cmds:
      - ./out/raytracer
    silent: true
  view:
    cmds:
      - explorer.exe image.png
    silent: true
